### ISSUE TITLE
Windows 10--no movement

### ISSUE THREAD

**Issue by zaheeroz** [LIU-Yinyi/PyRealSim#1]
Hi,
Thanks for uploading this, it really great work.
I tried to run the app on windows 10. I see all the 3 images with no errors, however the drone is not moving.
Am I missing something or its the window 10 issue ? 
I tried to connect the socket and send some data but it throws an error.
I am supposing after running the app, the quad needs to move or move once the app gets data from outside the app through sockets. If I am wrong could you please write a line or two on how to code is expected to behave. Thank you very much again.

**Comment by LIU-Yinyi** [comment]
Hi @zaheeroz ,

The API in `/api` directory was originally for Matlab.     
I am not sure if you used it in Matlab or coded a new app by following the protocol I defined in this project. 

- If the former situation, I just tested and everything went well. Maybe you could check the firewall configuration in order to allow some of temporary dynamic ports. 
- If the latter situation, I guess that the issue might be caused by the byte misalignment. Each of the socket package is **little-endian** and **8 bytes** for each item, including integer-like data. Protocol details are in `/engine/sim.py` [line 352](https://github.com/LIU-Yinyi/PyRealSim/blob/master/engine/sim.py#L352).

**Comment by zaheeroz** [comment]
Thanks LIU-Yinyi ,
It worked. I was using Python to send data not Matlab.
In Python to create a socket, I was using SOCK_STREAM instead of SOCK_DGRAM. When I changed it, I saw the drone flied with all its charm.
Thanks again :)
